project_id         = "your-gcp-project-id"
region             = "us-central1"
zone               = "us-central1-a"
network            = "voicing-dev-network"
instance_name      = "demo-vm"
machine_type       = "e2-medium"
disk_image         = "debian-cloud/debian-11"
startup_script_path = "./startup.sh"
tags = [ "voicing-ai", "dev" ]